### ISSUE TITLE
Remove override for `chrome-webstore-upload` when regular dependencies are updated

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#1100]
Overridden here:  https://github.com/melink14/rikaikun/blob/14c1c5c40cb19fb649195b784e46975397fe639e/package.json#L120

**Comment by melink14** [comment]
@SnoozeThis https://github.com/GabrielDuarteM/semantic-release-chrome/issues/94 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/9bH4JFc9NeE) I will wait until https://github.com/GabrielDuarteM/semantic-release-chrome/issues/94 is closed and then reassign to you (until at most Wed, 03 Aug 2022 07:34:47 UTC).

**Comment by melink14** [comment]
It turns out that we can use this override so I'll close this until another fix happens.
