### ISSUE TITLE
Remove override for `glob-parent` when dependencies are up to date normally

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#1101]
Overridden here: https://github.com/melink14/rikaikun/blob/14c1c5c40cb19fb649195b784e46975397fe639e/package.json#L121

**Comment by melink14** [comment]
@SnoozeThis https://github.com/runem/lit-analyzer/issues/213 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/4z9MymHlTa8) I will wait until https://github.com/runem/lit-analyzer/issues/213 is closed and then reassign to you (until at most Wed, 03 Aug 2022 07:36:15 UTC).

**Comment by SnoozeThis** [comment]
The deadline passed while snoozing.

**Comment by melink14** [comment]
@SnoozeThis https://github.com/runem/lit-analyzer/issues/213 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/NbYp3u_WIp4) I will wait until https://github.com/runem/lit-analyzer/issues/213 is closed and then reassign to you (until at most Tue, 06 Sep 2022 13:10:54 UTC).

**Comment by SnoozeThis** [comment]
The deadline passed while snoozing.

**Comment by melink14** [comment]
@SnoozeThis  https://github.com/runem/lit-analyzer/issues/213 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/qL6b0TRrH60) I will wait until https://github.com/runem/lit-analyzer/issues/213 is closed and then reassign to you (until at most Sat, 22 Oct 2022 04:30:34 UTC).

**Comment by SnoozeThis** [comment]
The deadline passed while snoozing.

**Comment by melink14** [comment]
@SnoozeThis https://github.com/runem/lit-analyzer/issues/213 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/LIbwYnuOWHw) I will wait until https://github.com/runem/lit-analyzer/issues/213 is closed and then reassign to you (until at most Sat, 17 Dec 2022 00:38:53 UTC).

**Comment by SnoozeThis** [comment]
The deadline passed while snoozing.

**Comment by melink14** [comment]
@SnoozeThis https://github.com/runem/lit-analyzer/issues/213 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/0dendrUaqD4) I will wait until https://github.com/runem/lit-analyzer/issues/213 is closed and then reassign to you (until at most Wed, 18 Jan 2023 07:19:28 UTC).

**Comment by SnoozeThis** [comment]
The deadline passed while snoozing.

**Comment by melink14** [comment]
According to the bug, maybe this is fixed by using lit-analyzer@next.
