### ISSUE TITLE
Make red outlines around okurigana in kanji entries optional

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [melink14/rikaikun#1120]
The following snapshot shows the red outlines/boxes around okurigana in kanji definition. Could you make it optional, or disable. These boxes are distracting.

![image](https://user-images.githubusercontent.com/24302271/177469164-61deaeb4-7dd9-43c3-8077-979e16d9ae41.png)

**Comment by melink14** [comment]
Honestly, this behavior was inherited from the version that this forked and I agree that it's probably not needed as long as the color matches. Should be easy to remove from the CSS (maybe a small HTML chagne too)

I would probably play with it in Dev Tools and then make the change.
