### ISSUE TITLE
I'm getting an error when inspecting the code on a page in Google Chrome

### ISSUE THREAD

**Issue by a4jp-com** [melink14/rikaikun#116]
chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/jquery-1.7.1.min.js:2 Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "http://www.thewindowsclub.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
(anonymous function) @ chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/jquery-1.7.1.min.js:2

**Comment by melink14** [comment]
That doesn't seem to be related to rikaikun except for the fact it's loaded
into the page.  My guess is that the version of jquery I'm loading is being
used by another app somehow.

I think there's a patch to remove jquery from rikaikun that would fix this.

2016年4月19日(火) 23:27 a4jp-com <notifications@github.com>:

**Comment by versusvoid** [comment]
Seems to be resolved?

**Comment by a4jp-com** [comment]
On the a4jp.com website I get this message when inspecting:

> Error in event handler for (unknown): IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 18 is larger than or equal to the node's length (10).
    at Object.highlightMatch (chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/rikaicontent.js:721:9)
    at processEntry (chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/rikaicontent.js:650:15)

>

**Comment by versusvoid** [comment]
@a4jp-com `z-index: 99999`, really? Looks like it's your site which is broken. :smile: 
This aside, I tried rikaikun on main page and have not met this error. Can you please specify exact page url (if it's other than main page) and piece of text you've hovered over? Do you use latest chrome version?

**Comment by a4jp-com** [comment]
I'll try and find a few other sites with the same problem too. I'm using version 56.0.2924.76 (64-bit) of Chrome. 

I just put the 99999 in the code to make it easy to search for while updating a few things. Thanks for reminding me about it though. ;)
