### ISSUE TITLE
Feature request: hover-and-key mode

### ISSUE THREAD

**Issue by b-d-m-p** [melink14/rikaikun#119]
Hi,

Thank you for the extension. Love it.

I would like to have Rikaikun on all the time but only see the popups when I am holding down a specific button. Would this be possible to make an option like this?

Cheers.

**Comment by b-d-m-p** [comment]
I see you just implemented this. Was this based on my suggestion?

**Comment by melink14** [comment]
This was done by a contributor who also wanted it.  is till need to upload it to Google though.

**Comment by melink14** [comment]
Fixed by @versusvoid in #117
