### ISSUE TITLE
FAQ wiki page is ugly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#12]
```
I need to figure out to use lists in such a way so that it looks nice.  Might 
just use html to do it I guess.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 6 Jan 2010 at 1:59

**Comment by nicolas-raoul** [comment]
It s also out of date.

The Chrome store description of the extension links to http://code.google.com/p/rikaikun/wiki/FAQ which is archived and read-only since  2015.

**Comment by melink14** [comment]
Duplicate of #156
