### ISSUE TITLE
Feature request: Japanese Dictionary

### ISSUE THREAD

**Issue by timsts** [melink14/rikaikun#123]
Thank you for the chrome port.  I really love it, especially since I am using a chromebook and cant use anything else.

Is it anyway possible to have an option to use Japanese definitions instead of English definitions.  I know I can turn off the English by pressing D or going into the settings, but having the Japanese definition readily available would be great.  It's an option in rikaichan, but not rikaikun.

Thanks
-Tim

**Comment by vintotal** [comment]
Je suis intéressé aussi, je voudrais utiliser le dictionnaire français. :-)

**Comment by melink14** [comment]
Duplicate of #146
