### ISSUE TITLE
Problem typing in Japanese with mouse in texting field, with rikaikun Activated

### ISSUE THREAD

**Issue by slowmowfit** [melink14/rikaikun#125]
Sorry, I was not able to find the way to post the Issue as you said.

So, let's say, when my cursor is already in the typing area, if I type in Japanese, the characters I will be writing will erase themselves by themselves. I will never be able to get a sentence as long as the start of it, until the place of the cursor. 

So the japanese text would be erased if the mouse is in the writing field, as I'd write at the same time...?

Does that make sense?

I don't have this issue with Rikaichan on Mozilla...

**Comment by versusvoid** [comment]
Please, present a link to page where you met such behavior.
