### ISSUE TITLE
「七夕」 has incorrect reading

### ISSUE THREAD

**Issue by pascaloettli** [melink14/rikaikun#129]
「七夕」 should be read 「たなばた」 and not「しちせき」.

**Comment by melink14** [comment]
That reading is given when I test it.  Is your complaint that the order of
the readings doesn't match common usage?

2017年7月6日(木) 23:50 Pascal Oettli <notifications@github.com>:

**Comment by pascaloettli** [comment]
Yes. Everybody says たなばて, not しらせき

**Comment by melink14** [comment]
Duplicate of #78
