### ISSUE TITLE
Add support for Kanji Learner's Dictionary 2nd Edition indices to rikaikun

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#1363]
This is in kanji dictionary data so I just need to whitelist it:
http://www.edrdg.org/wiki/index.php/KANJIDIC_Project#:~:text=Kanji%20Learners%20Dictionary%20number%20(2nd%20ed)

**Comment by tora-pan** [comment]
@melink14 for this one are you only adding the:
`code` , `name` , `shouldDisplay` to the `kanjiInfo` array?

Will you be adding an updated `kanji.dat` file that includes the `DL` numbers?

**Comment by melink14** [comment]
Yeah, for updating the kanji.dat we probably just need to update https://github.com/melink14/rikaikun/blob/b6e87d9bc2beb518ebef327448f5ec527f1884cb/utils/update-db.ts#LL49C30-L49C30 and then run the script to update the dictionaries.

The trick would be to do it such that the data update was only the additional reference and not additional new words.
