### ISSUE TITLE
Character hover not working on UDHR page

### ISSUE THREAD

**Issue by tobiowo** [melink14/rikaikun#138]
On the [Universal Declaration of Human Rights](http://www.ohchr.org/EN/UDHR/Pages/Language.aspx?LangID=jpn) page, no translation shows up when I hover over most of the characters.

I'm running the latest version of 64-bit Chrome on Windows 10.

**Comment by melink14** [comment]
It doesn't repro on OSX chrome so might be a font issue as we thought.

**Comment by melink14** [comment]
Can no longer repro on my windows 10 machine so I'm going to call this fixed now!
