### ISSUE TITLE
Not picking up most words in Google Translate text area

### ISSUE THREAD

**Issue by Ceiyne** [melink14/rikaikun#139]
I use Google Translate and Rikaikun every day and this just started happening this morning.

If I enter a Japanese sentence in the left hand side text box (the "original" text to be translated), I used to be able to mouse over any word in the sentence, and Rikaikun would properly pop up the translation.  Right now it's acting like it can only see one character or word in the text box and it only shows the pop-up for that.  It generally seems to be the second character in the text box.

Example: If I go to the following link, and attempt to use Rikaikun to translate words in the Japanese sentence on the left, it will only ever translate し (the second character in the sentence).

https://translate.google.com/#ja/en/%E3%82%82%E3%81%97%E4%BD%95%E3%81%8B%E5%95%8F%E9%A1%8C%E3%81%8C%E3%81%82%E3%82%8C%E3%81%B0%E3%80%81%E5%BD%BC%E3%81%AF%E7%A7%81%E3%81%AE%E5%8A%A9%E3%81%91%E3%82%92%E6%B1%82%E3%82%81%E3%81%9F%E3%81%A0%E3%82%8D%E3%81%86

Rikaikun seems to be working fine on any other Japanese page that I've tried, including both "regular" HTML text and pages with text entry features (e.g., Google Inbox "compose new mail").

I've tried looking at the Rikaikun options to see if I managed to turn something on that I shouldn't have, but nothing looks out of place.

I've also tried the basics: turning Rikaikun on/off, restarting Chrome, rebooting, etc.

**Comment by Ceiyne** [comment]
I have tested this on both Windows and a Chromebook, and I'm getting the same behavior in both places.

**Comment by melink14** [comment]
I just pushed a new update with a lot of changes from the last couple of years and it seems that commit #117 accidentally broke text area behavior.  Inbox may have some custom text areas that don't hit the bug but regular <textarea> tags like translate uses should trigger the bug.

I have a fix and hopefully will push it soon.

**Comment by melink14** [comment]
Fix should roll out shortly. Sorry for the breakage.

**Comment by Ceiyne** [comment]
Thanks, that was fast! :)
