### ISSUE TITLE
Hovering over ruby text pops up orangatang kanji

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#1417]
There's a code that returns empty string when hovering over ruby text. This empty string is passed through the logic and ends up returning the orangatang kanji at unicode 0000.

We should add a check to just return early in this case (and maybe reconsider hovering over ruby text?)

**Comment by tora-pan** [comment]
Here is a sample of the bug.
![Screenshot 2023-03-07 at 9 23 21 PM](https://user-images.githubusercontent.com/81494248/223626650-cf8b121b-40ce-4a15-b7d3-9faad02e789f.png)
