### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#160]
Type safety can prevent a lot of bugs and makes code easier to read and understand.

**Comment by ammgws** [comment]
What's the workload look like for this?

**Comment by melink14** [comment]
The official guidance is here: https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

The bare minimum is to just add the ts configuration to the project and rename the files to .ts.

They'll have various errors so the next step is to try to fix them; there's not actually that much code here so even doing it manually wouldn't be terrible but probably it would require something like:

1) Convert plain JS objects into classes and use imports to run code between modules. (should be easy hopefully)

2) Add types to functions (and download ts.d files for things like chrome extension APIs). There's probably less than 20 functions in rikaikun so not too bad.

Might also consider a converter: https://www.npmjs.com/package/js-to-ts-converter but might not be as useful since current code isn't even modern JS. Only did quick google search.

Also might be good to do this after some of the formatting tasks (and PR reviews) though for a small project probably not too hard to fix conflicts.

**Comment by melink14** [comment]
I have the initial PR for this but it doesn't actually idiomatically convert anything to typescript. Not sure if we should use this issue until all code is typescripted or just count it as finished when tyepscript works even if it's not compiling...
