### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by delbonis** [melink14/rikaikun#174]
It's be useful to know what this is licensed as :)

GPL pls

**Comment by melink14** [comment]
I should make a license file but it's currently GPL 2 (same as when I forked it from rikaichan) as listed in the top of the primary file:
https://github.com/melink14/rikaikun/blob/master/rikaichan.js

**Comment by melink14** [comment]
Will reopen until I create a LICENSE file.

**Comment by melink14** [comment]
Added the full GPL LICENSE to the root for now so I will close this.
