### ISSUE TITLE
Is there a way to make this work with readable pdfs.

### ISSUE THREAD

**Issue by joegonzalez722** [melink14/rikaikun#175]

**Comment by joegonzalez722** [comment]
[無題のドキュメント.pdf](https://github.com/melink14/rikaikun/files/4914903/default.pdf)

This a pdf of a book, all the text can be copied and pasted. Rikai kun has an option to work with offline files. It will work with txt files but won't with pdfs, epubs or html. Is there a way to fix this?

**Comment by melink14** [comment]
PDFs are opened inside a sandbox in chrome which means the content information isn't sent to rikaikun. (As far as I know)

Offline html files should work the same as offline txt files though I haven't tested it in awhile.

I'll keep this open for further investigation later though.

**Comment by ChocoChopin** [comment]
Have you tried installing a PDF browser extension that overrides Chrome's own reader? I imagine that would result in a page that's rendered in such a way that other extensions can get to it.

**Comment by joegonzalez722** [comment]
No, but it's okay, thanks for responding

2020年8月23日(日) 14:35 ChocoChopin <notifications@github.com>:

**Comment by melink14** [comment]
I did a bit of research here and I think the best we could do is have an option in the right click menu that took your currently selected text and displayd the result in the browser action popup (top right) or a system notification (seems worse).

Basically, we can do anything with the text once we get it, except display the results directly inside the PDF.

**Comment by joegonzalez722** [comment]
ok

2020年8月26日(水) 19:37 Erek Speed <notifications@github.com>:
