### ISSUE TITLE
Microsoft Edge release

### ISSUE THREAD

**Issue by crse** [melink14/rikaikun#209]
As the title stated above, I hope the addon will also be released on Edge Add-ons as well.

**Comment by melink14** [comment]
Yes, I have an email from them but I hadn't prioritized it since I was trying to fix some other low hanging fruit.

Though when I was prompted to setup the new Edge, it automatically installed all my chrome extensions so I thought maybe it wasn't necessary?

**Comment by melink14** [comment]
In progress, check back at https://partner.microsoft.com/en-us/dashboard/microsoftedge later.

**Comment by melink14** [comment]
This is now available at https://microsoftedge.microsoft.com/addons/detail/rikaikun/ebdggalafggfhdllgohjbpgnmfppdfih

Thanks!
