### ISSUE TITLE
Remove nonnull assertion operator from `inlineDisable`

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#2154]
https://github.com/melink14/rikaikun/blob/8fd4bf403742fd6041767c79d87f5e080aa6d033/extension/rikaichan.ts#L217-L222

This nonnull assertion operator seems unnecessary due to the guard above, but it seems like indexing into certain arrays means typescript is not sure something hasn't changed.

The workaround is to save the value to a variable before checking it. (ref https://stackoverflow.com/questions/75640224/type-narrowing-is-not-working-in-for-loop)

Interestingly this is already done for `tabs` in the previous block. One way to get a variable for free is to switch to a `for..of` loop which always gives each iteration a variable. I don' tthink we're using the index for anything else so that is probably the cleanest solution.

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! Just to clarify 1. is it fine to switch the 'windows' and 'tabs' loops to "for..of" loops and 2. in the tabs loop, save the tabId beforehand and use that directly instead of the nonnull assertion operator?

**Comment by melink14** [comment]
That sounds good to me. I saw your PR as well so I'll review it directly.
