### ISSUE TITLE
Not popup for google doc on microsoft edge

### ISSUE THREAD

**Issue by hsunwenfang** [melink14/rikaikun#2175]
**Describe the bug**
Not popup for google doc on microsoft edge 

**To Reproduce**
Install and use on Edge

**Expected behavior**
Popup on Edge contents

**Screenshots**

**System details (OS, browser version, rikaikun version)**

- OS: MacOS Sonoma 14.6
- Browser Version: Version 128.0.2739.42
- rikaikun Version: 3.0.0

**Additional context**

**Comment by melink14** [comment]
Thanks for reporting the issue. The root cause was new restrictions on how scripts can interact with web pages in manifest V3. I've tested a fix and it should be published within a day.

I'm still not sure why this didn't break in chrome though!
