### ISSUE TITLE
Refactor CSS to avoid duplication

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#222]
Right now for every style of popup, we have a different CSS which is 95% the same.

I think using CSS variables (or SASS if we need something fancy) would be a good way to have a single file with most of the CSS that uses variables that we can update via JS to set the theme.

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by melink14** [comment]
https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8 is a good guide on this.

**Comment by melink14** [comment]
Reasonable theming guide: https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8

Probably just have a set for each theme and set based on config when rendering popup. (this could also make it pretty easy to allow inserting custom CSS.
