### ISSUE TITLE
Remove patch to vite-multiple-assets once upstream is fixed

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#2330]
https://github.com/melink14/rikaikun/blob/main/patches/vite-multiple-assets%2B2.2.4.patch

We removed an extra duplicate interface so that tsc would work with no compilation errors.

@SnoozeThis https://github.com/nguyenbatranvan/vite-multiple-assets/issues/40 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/yBCzH4tzLqg) I will wait until https://github.com/nguyenbatranvan/vite-multiple-assets/issues/40 is closed and then reassign to you (until at most Sun, 19 Jan 2025 10:04:00 UTC).

**Comment by SnoozeThis** [comment]
Resolved.
