### ISSUE TITLE
Remove rollup dev dependency once upstream adds it themselves

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#2331]
https://github.com/melink14/rikaikun/blob/12f13870b53b78a7fe8d89337cde15ae04d97a62/package.json#L105

@SnoozeThis https://github.com/nguyenbatranvan/vite-multiple-assets/issues/42 <= 1 month

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/4j9sYvZL_3U) I will wait until https://github.com/nguyenbatranvan/vite-multiple-assets/issues/42 is closed and then reassign to you (until at most Sun, 19 Jan 2025 10:05:47 UTC).

**Comment by SnoozeThis** [comment]
Resolved.
