### ISSUE TITLE
Display Kanji in the same font as the page to prevent confusion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#53]
```
What steps will reproduce the problem?
1. Look at attached picture
2. Highlighted kanji and character shown in information screen differ. The 
query codes are correct.

What is the expected output? What do you see instead?
I expect to see the same kanji in the info screen.

What version of the product are you using? On what operating system?
0.8.1

Please provide any additional information below.
Could this be an old version of the kanji? I was unable to locate this shape in 
a dictionary.
```

Original issue reported on code.google.com by `mihail.p...@gmail.com` on 8 Apr 2011 at 9:48

Attachments:
- [wrong_kanji.jpg](https://storage.googleapis.com/google-code-attachments/rikaikun/issue-53/comment-0/wrong_kanji.jpg)

**Comment by melink14** [comment]
I don't think I realized this back in 2011 but this bug was probably a Chinese vs Japanese mismatch caused by `lang='ja'` on the rikaikun popup.

In that case, it doesn't make sense to fix this since it's caused by the webpage being misconfigured.
