### ISSUE TITLE
Convert Dictionaries to Chrome format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#6]
```
This is pretty easy since I was able to not change the format at all from 
Jon's.  But I just have to make extensions for them so people can use it the 
same way.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 5 Jan 2010 at 7:53

**Comment by melink14** [comment]
This one was pretty vague and was mostly about having separate extensions but I will close it and open a modern bug with new ideas.
