### ISSUE TITLE
"On" icon incorrectly displayed on startup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#82]
```
What steps will reproduce the problem?
1. Open chrome for first time
2. "On" icon displayed
3. Confirm that rikaikun is not actually on
4. Press the rikai button again to turn on
5. Observe that icon remains in "on" state and rikai kun is actually on

What is the expected output? What do you see instead?
Expect the icon to not display on when rikai kun is not on


What version of the product are you using? On what operating system?
 0.8.5
on chrome 22.0.1229.94 m
and windows 7 x86
```

Original issue reported on code.google.com by `perceptu...@gmail.com` on 15 Oct 2012 at 4:22

**Comment by melink14** [comment]
I think this is fixed at head...

**Comment by melink14** [comment]
Feel like I still see this so we need to confirm.

**Comment by melink14** [comment]
Confirm on fresh chrome starts it tends to happen. (or maybe just the first installation)

**Comment by melink14** [comment]
It seems that the badge state is preserved across restarts; so if it was on it will remain on; however since rikaikun always starts off, it means it's out of sync.
