### ISSUE TITLE
Getting translation by hovering over Japanese emails content on Gmail used to work.

### ISSUE THREAD

**Issue by sebjanek** [melink14/rikaikun#873]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details (OS, browser version, rikaikun version)**

- OS: [e.g. Windows 10, macOS Catalina]
- Browser Version: [e.g. Chrome 84]
- rikaikun Version: [e.g. 0.10.1]

**Additional context**

**Comment by melink14** [comment]
(Looks like this was opened at the same time as the other bug as a duplicate)
