### ISSUE TITLE
Not working on Gmail content anymore

### ISSUE THREAD

**Issue by sebjanek** [melink14/rikaikun#874]
**Describe the bug**
Getting translation by hovering over Japanese emails content on Gmail used to work. It started not working a week ago.

**To Reproduce**

1. Go to Gmail
2. Click on any email with Japanese language

**Expected behavior**
It used to work. I am expecting to get the translation while hovering on email Japanese text.

**Screenshots**

**System details (OS, browser version, rikaikun version)**

- OS: macOS Catalina 10.15.7
- Browser Version: Version 98.0.4758.109 (Official Build) (x86_64)
- rikaikun Version:2.2.0

**Comment by sebjanek** [comment]
works fine now. not sure the reason of the bug. It used to work everywhere except gmail. Now ok.

**Comment by melink14** [comment]
I'm glad it's working now! Sorry for the trouble.
