### ISSUE TITLE
でした not recognized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#89]
```
What steps will reproduce the problem?
1.It doesn't recognize "でした" (was/were);
2.In "Options", only "General" is active. 


What version of the product are you using? On what operating system?

Version 0.8.5, on Google Chrome.



```

Original issue reported on code.google.com by `ciccio.d...@gmail.com` on 23 Jul 2013 at 12:44

**Comment by melink14** [comment]
This seems to have changed. I would have thought でした would be deinflected to です but it doesn't seem to be so maybe there's another bug.

**Comment by melink14** [comment]
Should be easy to look at deinflection code and figure out what it does when given でした.

**Comment by maawisul** [comment]
I take a look at the dictionary and find that there is no entry for でした unlike です so any でした followed by nouns will not be recognized by the extension. (there is a ませんでした in deinflect.dat so verbs will be recognized correctly.) 

So should the fix still be implemented on the code or can I add an entry of でした directly in the dictionary files?

**Comment by maawisul** [comment]
![image](https://user-images.githubusercontent.com/83802443/164801210-7a072563-d226-485e-a02f-8344e021bf06.png)

I get rikaikun to recognize でした as です by adding one more conditional after line 495, 
https://github.com/maawisul/rikaikun/blob/47ff1a062f23713ab3ef2a6d9dc9b08295352f85/extension/data.ts#L496-L498

Should I submit a pull request?

**Comment by melink14** [comment]
I saw your PR so will look at it over there.

In general, for small changes sending PR is always fine since the worst that can happen is that changes are requested. Thanks for checking!

**Comment by melink14** [comment]
We decided that です was too different to reuse verb logic so the way forward is to add a definflection type for the copula as described in https://github.com/melink14/rikaikun/pull/988
