### ISSUE TITLE
Z-level control and sticky pop up feature requests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#92]
```
Please fix the bug about the pop up going behind flash videos or adverts!!!

Also a hotkey for keeping the pop up sticky so you can copy stuff from there 
would be useful:D
```

Original issue reported on code.google.com by `melin...@gmail.com` on 21 Nov 2013 at 6:49

**Comment by melink14** [comment]
The second part is covered by the copy command 'c'

The first part might be worth tracking separately but is mostly fixed we can track other examples. I'm not sure if we should track automatic detection of z-index problems as well. but won't for now.
