### ISSUE TITLE
Doesn't show English translations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#97]
```
Recently Rikaikun has stopped showing the English translations of highlighted 
words. I believe this may have begun occurring after the latest Google Chrome 
update. The version I have is 33.0.1750.154 m.

```

Original issue reported on code.google.com by `AHylto...@gmail.com` on 16 Mar 2014 at 4:01

**Comment by ichlubna** [comment]
I am encountering this now, seems like the same issue. Started a day ago or so.

![Image](https://github.com/user-attachments/assets/add07719-fa9a-4b07-a682-f0718f0c0e0c)

**Comment by melink14** [comment]
You might have disabled english definitions by accident ('d' hot key): Check the FAQ: https://github.com/melink14/rikaikun/wiki/FAQs#how-come-i-only-see-the-japanese-reading-with-no-english-definition

**Comment by ichlubna** [comment]
> You might have disabled english definitions by accident ('d' hot key)

You are right! I am really sorry for not reading the FAQ earlier. Thank you ^_^"
